# Generated by Django 6.0.4 on 2026-04-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Trimis la')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
            ],
            options={
                'verbose_name': 'Mesaj contact',
                'verbose_name_plural': 'Mesaje contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JetSki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('brand', models.CharField(max_length=100, verbose_name='Marcă')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='An')),
                ('slug', models.SlugField(blank=True, help_text='Generat automat. Nu modifica dacă nu știi ce faci.', max_length=250, null=True, unique=True, verbose_name='Slug URL')),
                ('engine', models.CharField(max_length=200, verbose_name='Motor')),
                ('horsepower', models.PositiveIntegerField(verbose_name='Cai putere')),
                ('condition', models.CharField(max_length=200, verbose_name='Stare')),
                ('status', models.CharField(choices=[('in_collection', 'În colecție'), ('available', 'Disponibil'), ('sold', 'Vândut'), ('favorite', 'Favorit')], default='in_collection', max_length=20, verbose_name='Status')),
                ('short_description', models.TextField(max_length=500, verbose_name='Descriere scurtă')),
                ('full_description', models.TextField(blank=True, verbose_name='Povestea acestui model')),
                ('why_worth_seeing', models.TextField(blank=True, verbose_name='De ce merită văzut')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='jetski/', verbose_name='Imagine principală')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL Video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Jet-Ski',
                'verbose_name_plural': 'Jet-Ski-uri',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JetSkiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jetski/gallery/', verbose_name='Imagine')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Descriere imagine')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine afișare')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adăugat la')),
                ('jetski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.jetski', verbose_name='Jet-Ski')),
            ],
            options={
                'verbose_name': 'Imagine galerie',
                'verbose_name_plural': 'Imagini galerie',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
