# Generated by Django 6.0.4 on 2026-04-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oraș')),
                ('owns_jetski', models.BooleanField(default=False, verbose_name='Deține jet-ski')),
                ('favorite_brand', models.CharField(blank=True, choices=[('sea-doo', 'Sea-Doo'), ('yamaha', 'Yamaha'), ('kawasaki', 'Kawasaki'), ('other', 'Alt brand'), ('none', 'Nu am încă')], max_length=20, verbose_name='Brand preferat')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj opțional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Înscris la')),
            ],
            options={
                'verbose_name': 'Înscriere comunitate',
                'verbose_name_plural': 'Înscrieri comunitate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nume categorie')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descriere')),
                ('icon', models.CharField(default='💬', max_length=10, verbose_name='Emoji icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine afișare')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
            ],
            options={
                'verbose_name': 'Categorie forum',
                'verbose_name_plural': 'Categorii forum',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopicPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu subiect')),
                ('slug', models.SlugField(blank=True, max_length=320, verbose_name='Slug URL')),
                ('author_name', models.CharField(default='Membru', max_length=100, verbose_name='Autor')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Răspunsuri')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vizualizări')),
                ('last_activity', models.DateTimeField(auto_now_add=True, verbose_name='Ultima activitate')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalog.forumcategory', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Subiect forum (preview)',
                'verbose_name_plural': 'Subiecte forum (preview)',
                'ordering': ['-is_pinned', '-last_activity'],
            },
        ),
    ]
