# Generated by Django 6.0.4 on 2026-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_communitywaitlist_forumcategory_forumtopicpreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu eveniment')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug URL')),
                ('location', models.CharField(max_length=200, verbose_name='Locatie')),
                ('event_date', models.DateField(verbose_name='Data eveniment')),
                ('short_description', models.TextField(max_length=500, verbose_name='Descriere scurta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagine eveniment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
            ],
            options={
                'verbose_name': 'Eveniment (preview)',
                'verbose_name_plural': 'Evenimente (preview)',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nume')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oras')),
                ('message', models.TextField(max_length=600, verbose_name='Mesaj')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Rating (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adaugat la')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimoniale',
                'ordering': ['-created_at'],
            },
        ),
    ]
