# Generated by Django 6.0.4 on 2026-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_eventpreview_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Cheie')),
                ('value', models.TextField(blank=True, verbose_name='Valoare')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descriere')),
                ('is_public', models.BooleanField(default=True, help_text='Valoarea este accesibila in template-uri', verbose_name='Public')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Setare site',
                'verbose_name_plural': 'Setari site',
                'ordering': ['key'],
            },
        ),
    ]
