# Generated by Django 6.0.4 on 2026-04-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitywaitlist',
            name='wants_updates',
            field=models.BooleanField(default=False, help_text='Bifat: vrea să primească noutăți despre lansare și evenimente', verbose_name='Dorește noutăți'),
        ),
    ]
