# Generated by Django 6.0.4 on 2026-04-27 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_communitywaitlist_wants_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oraș')),
                ('owns_jetski', models.BooleanField(default=False, verbose_name='Deține jet-ski')),
                ('favorite_brand', models.CharField(blank=True, choices=[('sea-doo', 'Sea-Doo'), ('yamaha', 'Yamaha'), ('kawasaki', 'Kawasaki'), ('other', 'Alt brand'), ('none', 'Nu am încă')], max_length=20, verbose_name='Brand preferat')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Despre mine')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Înregistrat la')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Profil membru',
                'verbose_name_plural': 'Profile membri',
                'ordering': ['-created_at'],
            },
        ),
    ]
