# Generated by Django 6.0.4 on 2026-04-27 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_memberprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='Slug URL')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vizualizări')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixat')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Blocat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_topics', to='catalog.forumcategory', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Subiect forum',
                'verbose_name_plural': 'Subiecte forum',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='catalog.forumtopic', verbose_name='Subiect')),
            ],
            options={
                'verbose_name': 'Răspuns forum',
                'verbose_name_plural': 'Răspunsuri forum',
                'ordering': ['created_at'],
            },
        ),
    ]
