# Generated by Django 6.0.4 on 2026-04-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_forumtopic_forumreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Șters la'),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Șters'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Șters la'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Șters'),
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam sau reclame'), ('offensive', 'Conținut ofensator'), ('misinformation', 'Informații false'), ('personal_data', 'Date personale expuse'), ('scam', 'Tentativă de înșelăciune'), ('other', 'Alt motiv')], max_length=30, verbose_name='Motiv')),
                ('details', models.TextField(blank=True, max_length=1000, verbose_name='Detalii suplimentare')),
                ('status', models.CharField(choices=[('new', 'Nou'), ('reviewed', 'Verificat'), ('dismissed', 'Respins')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Raportat la')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificat la')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.forumreply', verbose_name='Răspuns raportat')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reports', to=settings.AUTH_USER_MODEL, verbose_name='Raportat de')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.forumtopic', verbose_name='Subiect raportat')),
            ],
            options={
                'verbose_name': 'Raport forum',
                'verbose_name_plural': 'Rapoarte forum',
                'ordering': ['-created_at'],
            },
        ),
    ]
