# Generated by Django 6.0.4 on 2026-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_forumreply_deleted_at_forumreply_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='show_in_directory',
            field=models.BooleanField(default=True, verbose_name='Vizibil în directorul membrilor'),
        ),
    ]
