# Generated by Django 6.0.4 on 2026-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_contactmessage_phone_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug URL')),
                ('partner_type', models.CharField(choices=[('dealer', 'Dealer jet-ski'), ('service', 'Service / Reparații'), ('accessories', 'Accesorii & Echipamente'), ('rental', 'Închirieri'), ('event', 'Evenimente & Tururi'), ('other', 'Altele')], max_length=20, verbose_name='Tip partener')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oraș')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descriere scurtă')),
                ('full_description', models.TextField(blank=True, verbose_name='Descriere completă')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='partners/covers/', verbose_name='Imagine copertă')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Text badge')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Promovat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Partener',
                'verbose_name_plural': 'Parteneri',
                'ordering': ['order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nume business')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Persoană contact')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('partner_type', models.CharField(choices=[('dealer', 'Dealer jet-ski'), ('service', 'Service / Reparații'), ('accessories', 'Accesorii & Echipamente'), ('rental', 'Închirieri'), ('event', 'Evenimente & Tururi'), ('other', 'Altele')], max_length=20, verbose_name='Tip')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oraș')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Nou'), ('contacted', 'Contactat'), ('approved', 'Aprobat'), ('rejected', 'Respins')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Trimis la')),
            ],
            options={
                'verbose_name': 'Cerere partener',
                'verbose_name_plural': 'Cereri parteneri',
                'ordering': ['-created_at'],
            },
        ),
    ]
